# Languages configuration
# Documentation: https://docs.hugoblox.com/reference/language/

en:
  languageCode: en-us
  locale: en-us
  languageName: English
  weight: 1
  title: "Pierre Ramet"

fr:
  languageCode: fr-fr
  locale: fr-fr
  languageName: Français
  weight: 2
  title: "Pierre Ramet"
